spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/hotel}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}